### ISSUE TITLE
Poprawna obsługa zapytania o niepoprawne kroki

### ISSUE THREAD

**Issue by margap1998** [margap1998/ScenarioSEproject#10]
Jako analityk mogę sprawdzić, które kroki nie rozpoczynają się od aktora, który wykonuje czynność, aby móc poprawić błąd tego typu

* Pracochłonność: ~2 godziny

**Comment by piotrjurga** [comment]
Według specyfikacji odpowiedzią na to zapytanie jest lista niepoprawnych kroków, nie ich ilość, więc proponuję zmianę ScenarioIncorrectStepCountVisitor na ScenarioIncorrectStepListVisitor i odpowiednią modyfikację tej klasy.

**Comment by margap1998** [comment]
> 
> 
> Według specyfikacji odpowiedzią na to zapytanie jest lista niepoprawnych kroków, nie ich ilość,
>więc proponuję zmianę ScenarioIncorrectStepCountVisitor na ScenarioIncorrectStepListVisitor i
>odpowiednią modyfikację tej klasy.

No też, się skapnąłem. Już się zabieram

**Comment by piotrjurga** [comment]
Zapytanie obsługiwane pod `/api/incorrectStepList`, więc można uznać to za _naprawdę_ zamknięte.
