### ISSUE TITLE
Poprawna obsługa zapytania o tekst scenariusza

### ISSUE THREAD

**Issue by margap1998** [margap1998/ScenarioSEproject#11]
Jako analityk mogę pobrać scenariusz w postaci tekstu z numeracją kroków, aby móc włączyć go do dokumentacji
*Pracochłonność: ~3 godzin

**Comment by piotrjurga** [comment]
Napisałem klasę zwracającą tekst scenariusza (ScenarioToTextVisitator), pozostało tylko zintegrować ją z interfejsem REST.

**Comment by piotrjurga** [comment]
Zapytanie obsługiwane pod `/api/toText`.
