### ISSUE TITLE
Dostosowanie szkieletu

### ISSUE THREAD

**Issue by margap1998** [margap1998/ScenarioSEproject#2]
1. Pobranie projektu
2. Dopisanie niezbędnych informacji
3. Załadowanie

**Comment by piotrjurga** [comment]
Dostosowałem szkielet, dodałem `run.bat` do uruchamiania wyniku `mvn compile` na windowsie, jeżeli ktoś pracuje na linuxie zachęcam do dodania analogicznego `run.sh`.
