### ISSUE TITLE
Słowa Kluczowe

### ISSUE THREAD

**Issue by margap1998** [margap1998/ScenarioSEproject#21]
Jako analityk mogę sprawdzić ile kroków zawiera słowa kluczowe, aby dowiedzieć się jak wiele decyzji warunkowych znajduje się w scenariuszu

o Każdy krok w strukturze zaczynający się od słowa kluczowe zwiększa wynik o jeden
o Scenariusz wolny od kroków zaczynających się od słów kluczowych daje wynik zero

**Comment by piotrjurga** [comment]
Zapytanie obsługiwane pod `/api/keywordCount`.
