### ISSUE TITLE
Ograniczanie scenariuszy

### ISSUE THREAD

**Issue by margap1998** [margap1998/ScenarioSEproject#23]
Jako analityk mogę uzyskać scenariusz zawierający pod-scenariusze tylko do określonego poziomu, aby zaprezentować uproszczoną wersję wymagań

- Wejście stanowi struktura scenariusza oraz liczba określająca poziom
- Przy poziomie = 1 zwracany jest tylko scenariusz najwyższego poziomu
- Przy poziomach > 1 zwracane są scenariusze do danego poziomu włącznie (np. poziom = 2 oznacza scenariusz na najwyższym poziomie oraz jego bezpośrednie pod-scenariusze)

**Comment by piotrjurga** [comment]
Zapytanie obsługiwane pod `/api/keywordCount`.
