### ISSUE TITLE
Trello

### ISSUE THREAD

**Issue by margap1998** [margap1998/ScenarioSEproject#5]
Mamy zapisane Trello. Z tego co patrzyłem pobieżnie to narzędzie do wspomagania produktywności.
https://trello.com/tour

**Comment by piotrjurga** [comment]
Trzeba dopytać się prowadzącego czy na pewno musimy wykorzystać Trello żeby zaliczyć ten podpunkt bo prawdopodobnie wystarczy, że wykorzystamy Github Issues w tej samej roli (co już zaczęliśmy robić).

**Comment by margap1998** [comment]
Dostałem odpowiedź

>[...] Zgodnie z DoD-ami, GitHub Issues powinno wystarczyć. Proszę tylko pamiętać, aby uzupełniać je regularnie. Nie ukrywam, że Trello wydaje się po prostu wygodniejsze. [...]
