### ISSUE TITLE
Implementacja wewnętrznej struktury

### ISSUE THREAD

**Issue by margap1998** [margap1998/ScenarioSEproject#7]
Należy zdefiniować struktury danych w kodzie programu, aby można było przechowywać scenariusze, aktorów i przetwarzać je w naszej aplikacji.

**Comment by piotrjurga** [comment]
Wewnętrzna reprezentacja składa się z klas `Scenario` i `Step`, dodałem przykładowy scenariusz w formacie JSON `example_scenario.json`.
