### ISSUE TITLE
Poprawna obsługa zapytania o ilość kroków

### ISSUE THREAD

**Issue by margap1998** [margap1998/ScenarioSEproject#9]
Jako analityk mogę sprawdzić ile kroków zawiera cały scenariusz (łącznie z pod-scenariuszami), aby ocenić jak bardzo jest skomplikowany

**Comment by piotrjurga** [comment]
Zaimplementowałem klasę liczącą kroki (ScenarioStepCountVisitator), pozostało tylko wykorzystać ją w obsłudze odpowiednich zapytań RESTowych.

**Comment by piotrjurga** [comment]
Zapytanie obsługiwane pod `/api/stepCount`.
